/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xueguoliang_hc_Jni */

#ifndef _Included_cn_xueguoliang_hc_Jni
#define _Included_cn_xueguoliang_hc_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xueguoliang_hc_Jni
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xueguoliang_hc_Jni_Login
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cn_xueguoliang_hc_Jni
 * Method:    Reg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xueguoliang_hc_Jni_Reg
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     cn_xueguoliang_hc_Jni
 * Method:    LocationChange
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xueguoliang_hc_Jni_LocationChange
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cn_xueguoliang_hc_Jni
 * Method:    StartOrder
 * Signature: (DDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xueguoliang_hc_Jni_StartOrder
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
